config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :beers
  get 'home', to: 'application#home'
  get 'beers/type/:typ' => 'beers#index', as: 'beers_of_type'
  resources :drinkings
  resources :people
  get 'drinkings/new/:person' => 'drinkings#new', as: 'drinkings_newp'
  get 'drinkings/new/:beer' => 'drinkings#new', as: 'drinkings_newb'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord

   
   validates :name, 
              presence: true,
              length: {minimum: 3}
   
   ## tak tez mozna validates_length_of :name, minimum: 3


   belongs_to :beer_type, :class_name => "BeerType"
   has_many :drinkings


   def voltarz
      if vol.nil?
         return ""
      else
         return (vol*100).to_s.slice(0..3)+"%"
      end
   end 

   


   def voltarz=(value)
   	  self.vol = value.to_f/100.0
   end



   def high_voltarz?
   	 vol > 0.16
   end

   def high_voltarz!
   	 vol > 0.16
   	 save
   end


end

app/models/beer_type.rb
class BeerType < ApplicationRecord

  has_many :beers

end

app/models/drinking.rb
class Drinking < ApplicationRecord
	belongs_to :person
	belongs_to :beer , :class_name => "Beer"
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :drinkings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def home
    @result = "Jesteś w hołm"
  end

end

app/controllers/beer_types_controller.rb
class BeerTypesController < ApplicationController
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_action :prepare_record, only: [:show, :edit, :update]

  def prepare_record
      @t=BeerType.all
      @b=Beer.includes(:beer_type).find(params[:id])
  end  


  def show
    ##prepare_record

    #render action: 'page'   #app/views/beers/page.html.erb
    #defaultowo to bedzie  render  action: 'show'
    #lub po prostu: render 'page'  

    ###redirect_to(edit_beer_path) 

    ###redirect_to (home_path)

    respond_to do |format|
       format.html
       format.json { render json: @b }
       format.xml { render xml: @b }     #nie dziala, bo czegos tu brakuje
    end 
  end

  def edit
    ##prepare_record
  end  

  def update
     ##@b = Beer.find(params[:id])
     if @b.update(beer_params) 
        redirect_to (beers_path)    #moze byc tez  :beers
     else
        ##@t=BeerType.all
        flash[:notice] = "Jest źle"
        render 'edit'

        ###redirect_to (edit_beer_path) 

     end
  end

  #------------------------------------------

  def index
    if params[:typ]
     @t=BeerType.where(name: params[:typ]).first
     if @t.nil?
      @b=[]
     else
      @b=@t.beers
     end 
    else  
     @b=Beer.includes(:beer_type).all.order(name: :asc)
    end 
  end


  def destroy
    #usuwanie 
  end


  private
    def beer_params
       params.require(:beer).permit(:name, :voltarz, :beer_type_id) 
    end  

end

app/controllers/drinkings_controller.rb
class DrinkingsController < ApplicationController

	def index
	   @d=Drinking.includes(:person, :beer).all
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beer_types_helper.rb
module BeerTypesHelper

##   def format_vol(v)
##       if v===nil
##         return ""
##       else
##         return (v*100).to_s+"%"
##       end
##   end

end

app/helpers/beers_helper.rb
module BeersHelper

  def format_vol(v)
    if v===nil
       return ""
    else
      return (v*100).to_s+"%" 
    end
  end


end

app/helpers/drinkings_helper.rb
module DrinkingsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/application/home.html.erb
<h1>Home</h1>
<p>
	apllication#home zwrócił wartość: <strong> <%= @result %> </strong>
</p>

app/views/beers/_beer_errors.html.erb
<% if !(@b.nil?) %>
   <% if @b.errors.any? %>
        <div class="err">
        <div>
        	Form contains <%= pluralize(@b.errors.count, "error") %>.
        </div>
   	    <ul>
   		<% @b.errors.full_messages.each do |msg| %>
   		   <li>  <%= msg %> </li>
   		<% end %>
   		</ul>
   		</div>
   <% end %>
<% end %>

app/views/beers/edit.html.erb
<% if @b.nil? %>

<p class="err">Not found</p>

<% else %>

   <h1> Edycja </h1>

   <%= form_for(@b) do |piwo| %>
   
   <%= render 'beers/beer_errors', object: @b %>

   <table>
     <tr>
      <td><%= piwo.label :name %></td>
      <td><%= piwo.text_field :name %></td>
     </tr>

     <tr>
      <td><%= piwo.label :voltarz %></td>
      <td><%= piwo.text_field :voltarz %> </td>
     </tr>
   
     <tr>
     <td><%= piwo.label "Typ" %></td>
     <td><%= piwo.select :beer_type_id, @t.map {|x| [x.name, x.id]}, :default=>@b.beer_type_id %></td>
     </tr>
     <tr><td><%=  piwo.submit  %></td></tr> 
   </table>
   <% end  #form %> 

<% end %>

   <p></p>
   <a href="/beers">Powrót</a>

app/views/beers/index.html.erb
<h1> Beers </h1>

<% if @b.size==0 %>

   <h2> Sorry, no beers! </h2>

<% else %>

	<table border=1px>
	 <tr>
	  <th>Nazwa</th>
	  <th>Link (by link_to)</th>
	  <th>Voltarz</th>
	  <th>Typ</th>
	  <th></th>	
	  <th></th>
	 </tr>
	
	 <% @b.each do |p| %>
	 <tr> 
	  <td><a href="beers/<%= p.id %>"><%= p.name  %>   </a>            </td>
	  <td> <%=  link_to p.name, p, class: "myLink", confirm: "rili?"  %>  </td>
	  <td><%= p.voltarz  %>    </td>           
	  <td><%= p.beer_type.name  %>     </td>
	  <td><%=  link_to "edit", edit_beer_path(p) %></td>
	  <td><%=  link_to "delete", p, method: :delete, class: "myLink", data: {confirm: "Naprawdę?"}  %></td>          
	 </tr>    
	 <% end %>
	</table>

<% end %>

app/views/beers/page.html.erb
<h3> Tylko przykład dla render </h3>

app/views/beers/show.html.erb
<% if @b.nil? %>

<p class="err">Not found</p>


<% else %>

   <h1>Selected beer</h1>

   <!--p>Nazwa: <%= @b.name %> </p>
   <p>Voltarz: <%= format_vol(@b.vol) %> </p>
   <p>Typ: <%= @b.beer_type.name %> </p>

   <p> Metoda form_for </p-->

   <%= form_for(@b) do |p| %>
     
     <table>

     <tr>
     <td><%= p.label :name %></td>
     <td><%= p.text_field :name %></td>
     </tr>

     <tr>
     <td><%= p.label :voltarz %></td>
     <td><%= p.text_field :voltarz %> </td>
     </tr>

     <tr>
     <td><%= p.label "Typ" %></td>
     <td><%= p.select :beer_type_id, @t.map {|x| [x.name, x.id]}, :default=>@b.beer_type_id %></td>
     </tr>
     </table>

   <% end  #form %>

<% end %>

<p></p>
<a href="/beers">Return</a>

app/views/drinkings/index.html.erb
<h1> Drinknigs </h1>

<div style="position:relative; left:50px;"">
<table border=1>
	<% @d.each do |dx| %>
	  <tr>
	    <td><%= link_to "++", new_drinking_path %></td>	
	  	<td><%= link_to dx.person.name, dx.person %></td>	  
	  	<td><%= link_to dx.beer.name, dx.beer %></td>
	  	<td><%= dx.beer.beer_type.name  %></td>
	  	<td><%=  link_to "++"+dx.person.name  , drinkings_newp_url(dx.person.id) %> </td>
	    <td><%=  link_to "++"+dx.beer.name  , drinkings_newb_url(dx.beer.id) %> </td>
	  	<td><%= link_to "edit", edit_drinking_path(dx) %></td>
	  	<td><%= link_to "delete", dx, method: :delete, data: {confirm: "Serio?"} %></td>
	  </tr>
	<% end %>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice] %>
       <div id="notice" class="err"> <%= flash[:notice] %> </div>
    <% end%>

    <%= yield %>
  </body>
</html>